version: '3.8'

services:
  app:
    build: ./app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app # Montez le répertoire de l'application en tant que volume
      - /app/node_modules # Excluez les node_modules du volume pour éviter les conflits
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    command: npm run dev # Exécutez le script de développement avec hot reload

  api:
    build: ./api
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=strapi
    volumes:
      - db-data:/var/lib/postgresql/data

  strapi:
    build: ./strapi
    ports:
      - '1337:1337'
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=strapi
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    volumes:
      - ./strapi:/app
      - /opt/app/node_modules
    depends_on:
      - db
    command: sh -c "sleep 10 && npx strapi develop"

volumes:
  db-data:
